### ISSUE TITLE
[FEATURE] Can you add Gradle dependencies too

### ISSUE THREAD

**Issue by opticyclic** [myspotontheweb/ant2ivy#2]
Gradle can use directories as repositories as well as maven repositories.
Can you add the option for both?
For instance spring-aopalliance-1.0.jar would look like this in the two variants:

```
compile group: 'spring', name: 'spring-aopalliance', version: '1.0'
compile name: 'spring-aopalliance-1.0'
```

**Comment by myspotontheweb** [comment]
Resolved by

https://github.com/myspotontheweb/ant2ivy/pull/4
